### PR TITLE
[iOS] Picker not displayed when not on main view controller

### PR DESCRIPTION
**Pull request by dan15d**
Retrieve the top view controller from the view hierarchy and display picker.

In the current versión i get this error: 

Attempt to present <UIDocumentPickerViewController: 0x10c80ac00> on <_.MainViewController: 0x10a0099f0> (from <_.MainViewController: 0x10a0099f0>) whose view is not in the window hierarchy.

### CODE REVIEW

**Comment by MohamedRejeb** [comment]
Thanks for reporting that!
What about using `LocalUIViewController.current` is it going to fix the issue?

**Comment by dan15d** [comment]
Unfortunately, LocalUIViewController.current requires a @Composable context and the onLaunch callback of FilePickerLauncher doesn't have this context.

**Comment by MohamedRejeb** [comment]
Yes that's ok, it can be created on Compose:
val uiViewController = LocalUIViewController.current
and then passed to onLaunch, also it should be passed as a key to the remember

**Comment by dan15d** [comment]
That works! Do you want me to upload the changes?

**Comment by MohamedRejeb** [comment]
Yes

**Comment by MohamedRejeb** [comment]
It need to be added as a key to the remember as well:
```kotlin
...
    return remember(currentUiViewController) {
        FilePickerLauncher(
...
```

**Comment by MohamedRejeb** [comment]
Also, you forgot to push the import for `LocalUIViewController` I guess

**Comment by dan15d** [comment]
yes, i fix it. sorry

**Review by MohamedRejeb — APPROVED** [review]
Look good. Thanks for your contribution!

**Pull request merged**
