### PR TITLE
Update FilePickerLauncher.ios.kt

### PR DESCRIPTION
**Pull request by dan15d**
[IOS] Gallery picker only call onResult one time (like in file picker)

### CODE REVIEW

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for your contribution!
I will check this later today, can you explain how onResult can called twice?. How can I reproduce it.

**Comment by dan15d** [comment]
In iOS, when using the gallery image picker to select multiple images (2 or more), the onResult callback is expected to return a list of files. However, currently, it triggers the onResult callback multiple times (n times), each time with a list containing only a single image.

**Comment by dan15d** [comment]
I Use the Image/video picker

**Comment by MohamedRejeb** [comment]
I did some refactoring to your code using coroutines, feel free to check it out here: #129

**Pull request merged**
