### PR TITLE
Use PHPicker if file type is image on iOS

### LINKED ISSUE #35: File Picker Opening Recents Screen in iOS
# File Picker is opening the Recents Screen in iOS, unlike the gallery screen as shown in the Repository Readme.

## Screen which is being Opened
Screenshot 2023-10-26 at 6 33 30 PM

## Screen which should be Opened
image

### PR DESCRIPTION
**Pull request by iruizmar**
Closes #35 

I just copied the logic you previously had to use the PHPicker, but it's running only if the desired file type is an image.

Let me know if something else is required. Maybe a different screen in the sample to select an image or a pdf and thus check that the document picker is correctly run would be good.

image

### CODE REVIEW

**Review by MohamedRejeb — APPROVED** [review]

**Comment by MohamedRejeb** [comment]
Looks good! Thanks for your contribution.

**Comment by MohamedRejeb** [comment]
Yes, I think it would be a good idea if you can add a new screen with a pdf picker to have both pickers in the sample.

**Review by MohamedRejeb — APPROVED** [review]
Thanks for your contribution!

**Comment by iruizmar** [comment]
Hey @MohamedRejeb 👋🏻 
Thanks for that.
I added the screen to check the behaviour of selecting images or files and added a fancy switch to decide if the launcher should allow single or multiple selections.
This led me to find that the file picker is not working properly on Android. Do you want me to open an issue for that?

**Comment by MohamedRejeb** [comment]
I'll merge it, I was just waiting for the build result.
Yes, please open an issue for that, I will check it out.

**Pull request merged**
